In [6]:
import pandas as pd

In [9]:
df = pd.read_csv('data/data.csv')
df

C:\Users\HP\AppData\Local\Temp\ipykernel_14848\4179696218.py:1: DtypeWarning: Columns (0: accident_date) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/data.csv')

,accident_date,official_death_date,age,gender,nationality,accident_cause_code,accident_cause,vehicle_type,province_th,district_th,sub_district_th,province_en,district_en,sub_district_en,latitude,longitude
0,2011-01-01 00:25:00,2011-01-01,21.0,Male,Thai,V892,Person injured in unspecified motor-vehicle ac...,unidentified,เพชรบูรณ์,บึงสามพัน,บึงสามพัน,Phetchabun,Bueng Sam Phan,Bueng Sam Phan,15.794114,101.006878
1,2011-01-01 06:35:00,2011-01-01,23.0,Male,Thai,V299,Motorcycle rider [any] injured in unspecified ...,moterbike,สุราษฎร์ธานี,พนม,พังกาญจน์,Surat Thani,Phanom,Phangkan,8.916207,98.890434
2,2011-01-01 19:00:00,2011-01-01,26.0,Male,Thai,V234,Motorcycle rider injured in collision with car...,moterbike,ระยอง,บ้านฉาง,บ้านฉาง,Rayong,Ban Chang,Ban Chang,12.734329,101.065845
3,2011-01-01 02:00:00,2011-01-01,16.0,Male,Thai,V429,Car occupant injured in collision with two-or ...,car,พิษณุโลก,บางระกำ,ปลักแรด,Phitsanulok,Bang Rakam,Plak Rad,16.662980,100.120976
4,2011-01-01 02:00:00,2011-01-01,12.0,Male,Thai,V429,Car occupant injured in collision with two-or ...,car,พิษณุโลก,บางระกำ,ปลักแรด,Phitsanulok,Bang Rakam,Plak Rad,16.662980,100.120976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240919,NaN,2022-01-03,30.0,Male,Unknown,Unknown,Unknown,unidentified,นครราชสีมา,ไม่ระบุ,ไม่ระบุ,Nakhon Ratchasima,Unknown,Unknown,15.057413,102.347003
240920,NaN,2022-01-03,74.0,Female,Unknown,Unknown,Unknown,tricycle,อุดรธานี,ไม่ระบุ,ไม่ระบุ,Udon Thani,Unknown,Unknown,17.682571,103.193136
240921,NaN,2022-01-02,43.0,Female,Unknown,Unknown,Unknown,moterbike,จันทบุรี,ไม่ระบุ,ไม่ระบุ,Chanthaburi,Unknown,Unknown,12.505357,102.155707
240922,NaN,2022-01-01,NaN,Male,Unknown,Unknown,Unknown,unidentified,เพชรบูรณ์,ไม่ระบุ,ไม่ระบุ,Phetchabun,Unknown,Unknown,15.610476,101.061989
240923,NaN,2022-01-01,34.0,Female,Unknown,Unknown,Unknown,small_truck_or_van,นครราชสีมา,ไม่ระบุ,ไม่ระบุ,Nakhon Ratchasima,Unknown,Unknown,15.509395,102.683963

In [21]:
df.head()       # first 5 rows
df.tail()       # last 5 rows
df.sample(5)    # 5 random rows

,accident_date,official_death_date,age,gender,nationality,accident_cause_code,accident_cause,vehicle_type,province_th,district_th,sub_district_th,province_en,district_en,sub_district_en,latitude,longitude
214639,NaN,2021-12-10,12.0,Female,Thai,V249,Motorcycle rider injured in collision with hea...,moterbike,บุรีรัมย์,ไม่ระบุ,ไม่ระบุ,Buri Ram,Unknown,Unknown,14.854672,102.965577
62623,NaN,2013-09-09,50.0,Male,Thai,V299,Motorcycle rider [any] injured in unspecified ...,moterbike,อุบลราชธานี,ไม่ระบุ,ไม่ระบุ,Ubon Ratchathani,Unknown,Unknown,15.248977,104.880510
105489,NaN,2015-11-21,14.0,Male,Unknown,V299,Motorcycle rider [any] injured in unspecified ...,moterbike,ยะลา,ไม่ระบุ,ไม่ระบุ,Yala,Unknown,Unknown,6.398569,101.263622
70987,2014-10-26 12:00:00,2014-10-28,80.0,Male,Unknown,V234,Motorcycle rider injured in collision with car...,moterbike,เชียงราย,จุน,ทุ่งรวงทอง,Chiang Rai,Jun,Thung Ruang Thong,19.461415,100.158821
238636,NaN,2022-03-06,64.0,Male,Unknown,Unknown,Unknown,moterbike,นครราชสีมา,ไม่ระบุ,ไม่ระบุ,Nakhon Ratchasima,Unknown,Unknown,14.989526,102.064238

In [20]:
df.shape

(240924, 16)

In [14]:
df.info()       # column names, data types, how many non-null values
df.dtypes       # just the data types
df.columns      # just the column names

<class 'pandas.DataFrame'>
RangeIndex: 240924 entries, 0 to 240923
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   accident_date        106950 non-null  str
 1   official_death_date  240924 non-null  str
 2   age                  211110 non-null  float64
 3   gender               240924 non-null  str
 4   nationality          240924 non-null  str
 5   accident_cause_code  240924 non-null  str
 6   accident_cause       240924 non-null  str
 7   vehicle_type         240924 non-null  str
 8   province_th          240924 non-null  str
 9   district_th          240924 non-null  str
 10  sub_district_th      240924 non-null  str
 11  province_en          240924 non-null  str
 12  district_en          240924 non-null  str
 13  sub_district_en      240924 non-null  str
 14  latitude             240924 non-null  float64
 15  longitude            240924 non-null  float64
dtypes: float64(3), str(13)
memory usage: 29.4 MB

Index(['accident_date', 'official_death_date', 'age', 'gender', 'nationality',
       'accident_cause_code', 'accident_cause', 'vehicle_type', 'province_th',
       'district_th', 'sub_district_th', 'province_en', 'district_en',
       'sub_district_en', 'latitude', 'longitude'],
      dtype='str')

In [16]:
df.isnull().sum()    # count of missing values per column

accident_date          133974
official_death_date         0
age                     29814
gender                      0
nationality                 0
accident_cause_code         0
accident_cause              0
vehicle_type                0
province_th                 0
district_th                 0
sub_district_th             0
province_en                 0
district_en                 0
sub_district_en             0
latitude                    0
longitude                   0
dtype: int64

In [17]:
df.describe()
df.describe(include='all')

,accident_date,official_death_date,age,gender,nationality,accident_cause_code,accident_cause,vehicle_type,province_th,district_th,sub_district_th,province_en,district_en,sub_district_en,latitude,longitude
count,106950,240924,211110.000000,240924,240924,240924,240924,240924,240924,240924,240924,240924,240924,240924,240924.000000,240924.000000
unique,91871,4383,NaN,3,46,332,325,10,78,910,5909,78,1108,6098,NaN,NaN
top,2017-01-02 13:50:00,2012-01-01,NaN,Male,Thai,V892,Person injured in unspecified motor-vehicle ac...,unidentified,นครราชสีมา,ไม่ระบุ,ไม่ระบุ,Nakhon Ratchasima,Unknown,Unknown,NaN,NaN
freq,14,137,NaN,184157,132542,83595,83595,114446,10942,128951,129418,10942,129421,129421,NaN,NaN
mean,NaN,NaN,39.945531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.386777,101.023069
std,NaN,NaN,19.890274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.119720,2.972680
min,NaN,NaN,-22.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-74.389096,-92.511648
25%,NaN,NaN,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.526773,99.834848
50%,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.834059,100.657567
75%,NaN,NaN,55.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.377470,102.064238
max,NaN,NaN,154.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.822144,105.599818

In [18]:
df.duplicated().sum()    # how many duplicate rows exist

np.int64(2478)

In [23]:
print("Before:", df.shape)               # check before
df = df.drop_duplicates()                # remove duplicates
print("After:", df.shape)                # check after
print("Duplicates left:", df.duplicated().sum())  # should be 0

Before: (240924, 16)
After: (238446, 16)
Duplicates left: 0